### ISSUE TITLE
Cassandra::Client does not compile on Windows and MinGW with Perl 5.38.2

### ISSUE THREAD

**Issue by i-shenl** [TvdW/perl-DBD-Cassandra#37]
The following error below occurs on Windows and MinGW when trying to build and install Cassandra-Client with Perl 5.38.2. The function involved in this error is bswap2() but the same error also occurs with bswap4(). Will submit a patch that is working for me. 

In file included from decode.c:3:
swap.h: In function 'bswap2':
C:\builds\deps\1\installdir\lib\CORE/perl.h:204:17: error: 'my_perl' undeclared (first use in this function)
  204 | #  define aTHX  my_perl
      |                 ^~~~~~~
C:\builds\deps\1\installdir\lib\CORE/embedvar.h:23:49: note: in expansion of macro 'aTHX'
   23 | # define vTHX                                   aTHX
      |                                                 ^~~~
C:\builds\deps\1\installdir\lib\CORE/embedvar.h:276:50: note: in expansion of macro 'vTHX'
  276 | # define PL_Sock                                (vTHX->ISock)
      |                                                  ^~~~
C:\builds\deps\1\installdir\lib\CORE/iperlsys.h:1273:11: note: in expansion of macro 'PL_Sock'
 1273 |         (*PL_Sock->pNtohs)(PL_Sock, x)
      |           ^~~~~~~
C:\builds\deps\1\installdir\lib\CORE/XSUB.h:620:33: note: in expansion of macro 'PerlSock_ntohs'
  620 | #    define ntohs               PerlSock_ntohs
      |                                 ^~~~~~~~~~~~~~
swap.h:44:15: note: in expansion of macro 'ntohs'
   44 |     *the_num= ntohs(*the_num);
      |               ^~~~~
C:\builds\deps\1\installdir\lib\CORE/perl.h:204:17: note: each undeclared identifier is reported only once for each function it appears in
  204 | #  define aTHX  my_perl
      |                 ^~~~~~~
C:\builds\deps\1\installdir\lib\CORE/embedvar.h:23:49: note: in expansion of macro 'aTHX'
   23 | # define vTHX                                   aTHX
      |                                                 ^~~~
C:\builds\deps\1\installdir\lib\CORE/embedvar.h:276:50: note: in expansion of macro 'vTHX'
  276 | # define PL_Sock                                (vTHX->ISock)
      |                                                  ^~~~
C:\builds\deps\1\installdir\lib\CORE/iperlsys.h:1273:11: note: in expansion of macro 'PL_Sock'
 1273 |         (*PL_Sock->pNtohs)(PL_Sock, x)
      |           ^~~~~~~
C:\builds\deps\1\installdir\lib\CORE/XSUB.h:620:33: note: in expansion of macro 'PerlSock_ntohs'
  620 | #    define ntohs               PerlSock_ntohs
      |                                 ^~~~~~~~~~~~~~
swap.h:44:15: note: in expansion of macro 'ntohs'
   44 |     *the_num= ntohs(*the_num);
      |               ^~~~~
gmake: *** [Makefile:403: decode.o] Error 1
